name: kotha_boli
description: This is a chat application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  shared_preferences: ^2.1.1
  google_fonts: ^5.0.0
  get: ^4.6.5
  dots_indicator: ^3.0.0
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
   - assets/images/

  # https://flutter.dev/assets-and-images/#resolution-aware

  # https://flutter.dev/assets-and-images/#from-packages


  # see https://flutter.dev/custom-fonts/#from-packages
